/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 animationfixed.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/animationfixed-transformed.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    // console.log(actions)
    actions.KeyBoardTyper.play()
    actions.GridAction.play()
    actions.CatRobot.play()
    // actions.upanddown.play()
    actions.FirstLamp.play()
    actions.SecondLamp.play()
    actions.LampFour.play()
    actions.LampFive.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-1.35, 0.04, 1.61]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Beta_Surface" geometry={nodes.Beta_Surface.geometry} material={materials['Beta_HighLimbsGeoSG3.001']} skeleton={nodes.Beta_Surface.skeleton} />
          <skinnedMesh name="Beta_Joints" geometry={nodes.Beta_Joints.geometry} material={materials['Beta_Joints_MAT1.001']} skeleton={nodes.Beta_Joints.skeleton} />
        </group>
        <group name="Armature001" position={[-2.63, 2.86, 0.49]} rotation={[0, Math.PI / 2, 0]} scale={0.1}>
          <primitive object={nodes.Bone} />
          <skinnedMesh name="Sphere003_Material001_0" geometry={nodes.Sphere003_Material001_0.geometry} material={materials.Material} skeleton={nodes.Sphere003_Material001_0.skeleton} />
          <skinnedMesh name="Sphere003_Material001_0001" geometry={nodes.Sphere003_Material001_0001.geometry} material={materials['Material.040']} skeleton={nodes.Sphere003_Material001_0001.skeleton} />
          <skinnedMesh name="Sphere003_Material001_0002" geometry={nodes.Sphere003_Material001_0002.geometry} material={materials['Material.033']} skeleton={nodes.Sphere003_Material001_0002.skeleton} />
          <skinnedMesh name="Sphere003_Material001_0003" geometry={nodes.Sphere003_Material001_0003.geometry} material={materials['Material.033']} skeleton={nodes.Sphere003_Material001_0003.skeleton} />
          <skinnedMesh name="Sphere003_Material001_0004" geometry={nodes.Sphere003_Material001_0004.geometry} material={materials['Material.009']} skeleton={nodes.Sphere003_Material001_0004.skeleton} />
          <skinnedMesh name="Sphere003_Material001_0005" geometry={nodes.Sphere003_Material001_0005.geometry} material={materials['Material.009']} skeleton={nodes.Sphere003_Material001_0005.skeleton} />
          <skinnedMesh name="Sphere003_Material001_0006" geometry={nodes.Sphere003_Material001_0006.geometry} material={materials['Material.040']} skeleton={nodes.Sphere003_Material001_0006.skeleton} />
          <skinnedMesh name="Sphere003_Material001_0007" geometry={nodes.Sphere003_Material001_0007.geometry} material={materials['Material.041']} skeleton={nodes.Sphere003_Material001_0007.skeleton} />
          <skinnedMesh name="Sphere003_Material001_0008" geometry={nodes.Sphere003_Material001_0008.geometry} material={materials['Material.041']} skeleton={nodes.Sphere003_Material001_0008.skeleton} />
        </group>
        <group name="Cube005" position={[-1.87, 1, 1.53]} scale={0.71}>
          <mesh name="Cube007_1" geometry={nodes.Cube007_1.geometry} material={materials['Material.001']} />
          <mesh name="Cube007_2" geometry={nodes.Cube007_2.geometry} material={materials['Material.003']} />
          <mesh name="Cube007_3" geometry={nodes.Cube007_3.geometry} material={materials.floor} />
          <mesh name="Cube007_4" geometry={nodes.Cube007_4.geometry} material={materials['Material.003']} />
          <mesh name="Cube007_5" geometry={nodes.Cube007_5.geometry} material={materials['Material.002']} />
          <mesh name="Cube007_6" geometry={nodes.Cube007_6.geometry} material={materials['Material.003']} />
          <mesh name="Cube007_7" geometry={nodes.Cube007_7.geometry} material={materials.glass} />
          <mesh name="Cube007_8" geometry={nodes.Cube007_8.geometry} material={materials['Material.007']} />
          <mesh name="Cube007_9" geometry={nodes.Cube007_9.geometry} material={materials['Material.010']} />
          <mesh name="Cube007_10" geometry={nodes.Cube007_10.geometry} material={materials['Material.009']} />
          <mesh name="Cube007_11" geometry={nodes.Cube007_11.geometry} material={materials['Material.003']} />
          <mesh name="Cube007_12" geometry={nodes.Cube007_12.geometry} material={materials['Material.012']} />
          <mesh name="Cube007_13" geometry={nodes.Cube007_13.geometry} material={materials['Material.014']} />
        </group>
        <group name="Grid" position={[0.53, 2.51, -2.41]} rotation={[0, -0.88, 0]} scale={0}>
          <mesh name="Mesh002" geometry={nodes.Mesh002.geometry} material={materials.Grid} />
          <mesh name="Mesh002_1" geometry={nodes.Mesh002_1.geometry} material={materials.Land} />
        </group>
        <group name="Cube004" position={[-1.22, 0.69, 1.6]} scale={0.71}>
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials['Material.003']} />
        </group>
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials['Material.004']} position={[-1.87, 1, 1.53]} scale={0.71} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.016']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials['Material.016']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials['Material.015']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={materials['Material.017']} position={[-1.78, 0.02, 2.78]} scale={0.04} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials['Material.017']} position={[0.14, 0, 0.02]} scale={[0.1, 0.04, 0.04]} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={materials['Material.009']} position={[-1.87, 1, 1.53]} scale={0.71} />
        <mesh name="video_2022-10-24_09-31-17" geometry={nodes['video_2022-10-24_09-31-17'].geometry} material={materials['video_2022-10-24_09-31-17']} position={[-2.56, 1.43, 1.98]} rotation={[Math.PI / 2, 0, -1.63]} scale={[0.43, 0.43, 0.4]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.017']} position={[0.33, 0.4, -0.91]} rotation={[Math.PI / 2, 0, 0]} scale={[0.08, 0.08, 0.03]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.017']} position={[0.33, 0.4, -0.91]} rotation={[Math.PI / 2, 0, 0]} scale={[0.08, 0.08, 0.03]} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.017']} position={[0.33, 0.4, -0.91]} rotation={[Math.PI / 2, 0, 0]} scale={[0.08, 0.08, 0.03]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.017']} position={[0.33, 0.4, -0.91]} rotation={[Math.PI / 2, 0, 0]} scale={[0.08, 0.08, 0.03]} />
        <group name="GEO-vincent_button_03001" position={[-9.8, -0.8, 10.44]}>
          <mesh name="GEO-vincent_button_03001_1" geometry={nodes['GEO-vincent_button_03001_1'].geometry} material={materials['Material.009']} morphTargetDictionary={nodes['GEO-vincent_button_03001_1'].morphTargetDictionary} morphTargetInfluences={nodes['GEO-vincent_button_03001_1'].morphTargetInfluences} />
          <mesh name="GEO-vincent_button_03001_2" geometry={nodes['GEO-vincent_button_03001_2'].geometry} material={materials['Material.009']} morphTargetDictionary={nodes['GEO-vincent_button_03001_2'].morphTargetDictionary} morphTargetInfluences={nodes['GEO-vincent_button_03001_2'].morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/animationfixed-transformed.glb')
